services:

  frontend:
    build:
      context: ./jplab-frontend
    container_name: frontend
    ports:
      - "3001:3000"
    volumes:
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV= development


  backend:
    build:
      context: ./jplab-backend
    container_name: backend
    working_dir: /var/www/backend
    volumes:
      - ./jplab-backend:/var/www/backend
    command: php-fpm
    expose:
      - "9000"
    depends_on:
      - "db"


  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
      - ./jplab-backend:/var/www/backend
    depends_on:
      - backend
    restart: always

  db:
    image: mysql:8
    container_name: db-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jplab_db
      MYSQL_USER: jplab_user
      MYSQL_PASSWORD: 12345
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db-server
      PMA_PORT: 3306
    ports:
      - "8090:80"

volumes:
  dbdata:
  frontend_node_modules: